// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tobike.proto

package eu.trentorise.smartcampus.service.tobike.data.message;

public final class Tobike {
  private Tobike() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StazioneOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string codice = 1;
    boolean hasCodice();
    String getCodice();
    
    // required string nome = 2;
    boolean hasNome();
    String getNome();
    
    // required string indirizzo = 3;
    boolean hasIndirizzo();
    String getIndirizzo();
    
    // required double latitude = 4;
    boolean hasLatitude();
    double getLatitude();
    
    // required double longitude = 5;
    boolean hasLongitude();
    double getLongitude();
    
    // required string stato = 6;
    boolean hasStato();
    String getStato();
    
    // required int32 posti = 7;
    boolean hasPosti();
    int getPosti();
    
    // required int32 biciclette = 8;
    boolean hasBiciclette();
    int getBiciclette();
  }
  public static final class Stazione extends
      com.google.protobuf.GeneratedMessage
      implements StazioneOrBuilder {
    // Use Stazione.newBuilder() to construct.
    private Stazione(Builder builder) {
      super(builder);
    }
    private Stazione(boolean noInit) {}
    
    private static final Stazione defaultInstance;
    public static Stazione getDefaultInstance() {
      return defaultInstance;
    }
    
    public Stazione getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.tobike.data.message.Tobike.internal_static_eu_trentorise_smartcampus_service_tobike_data_message_Stazione_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.tobike.data.message.Tobike.internal_static_eu_trentorise_smartcampus_service_tobike_data_message_Stazione_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string codice = 1;
    public static final int CODICE_FIELD_NUMBER = 1;
    private java.lang.Object codice_;
    public boolean hasCodice() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getCodice() {
      java.lang.Object ref = codice_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          codice_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCodiceBytes() {
      java.lang.Object ref = codice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        codice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string nome = 2;
    public static final int NOME_FIELD_NUMBER = 2;
    private java.lang.Object nome_;
    public boolean hasNome() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nome_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string indirizzo = 3;
    public static final int INDIRIZZO_FIELD_NUMBER = 3;
    private java.lang.Object indirizzo_;
    public boolean hasIndirizzo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getIndirizzo() {
      java.lang.Object ref = indirizzo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          indirizzo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIndirizzoBytes() {
      java.lang.Object ref = indirizzo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        indirizzo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required double latitude = 4;
    public static final int LATITUDE_FIELD_NUMBER = 4;
    private double latitude_;
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getLatitude() {
      return latitude_;
    }
    
    // required double longitude = 5;
    public static final int LONGITUDE_FIELD_NUMBER = 5;
    private double longitude_;
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public double getLongitude() {
      return longitude_;
    }
    
    // required string stato = 6;
    public static final int STATO_FIELD_NUMBER = 6;
    private java.lang.Object stato_;
    public boolean hasStato() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getStato() {
      java.lang.Object ref = stato_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          stato_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStatoBytes() {
      java.lang.Object ref = stato_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        stato_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 posti = 7;
    public static final int POSTI_FIELD_NUMBER = 7;
    private int posti_;
    public boolean hasPosti() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getPosti() {
      return posti_;
    }
    
    // required int32 biciclette = 8;
    public static final int BICICLETTE_FIELD_NUMBER = 8;
    private int biciclette_;
    public boolean hasBiciclette() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getBiciclette() {
      return biciclette_;
    }
    
    private void initFields() {
      codice_ = "";
      nome_ = "";
      indirizzo_ = "";
      latitude_ = 0D;
      longitude_ = 0D;
      stato_ = "";
      posti_ = 0;
      biciclette_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCodice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNome()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIndirizzo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStato()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosti()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBiciclette()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCodiceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNomeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIndirizzoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, latitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, longitude_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getStatoBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, posti_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, biciclette_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCodiceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNomeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIndirizzoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, latitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, longitude_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getStatoBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, posti_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, biciclette_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.tobike.data.message.Tobike.StazioneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.tobike.data.message.Tobike.internal_static_eu_trentorise_smartcampus_service_tobike_data_message_Stazione_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.tobike.data.message.Tobike.internal_static_eu_trentorise_smartcampus_service_tobike_data_message_Stazione_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        codice_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nome_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        indirizzo_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        stato_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        posti_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        biciclette_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione build() {
        eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione buildPartial() {
        eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione result = new eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.codice_ = codice_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nome_ = nome_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.indirizzo_ = indirizzo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.stato_ = stato_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.posti_ = posti_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.biciclette_ = biciclette_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione) {
          return mergeFrom((eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione other) {
        if (other == eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione.getDefaultInstance()) return this;
        if (other.hasCodice()) {
          setCodice(other.getCodice());
        }
        if (other.hasNome()) {
          setNome(other.getNome());
        }
        if (other.hasIndirizzo()) {
          setIndirizzo(other.getIndirizzo());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasStato()) {
          setStato(other.getStato());
        }
        if (other.hasPosti()) {
          setPosti(other.getPosti());
        }
        if (other.hasBiciclette()) {
          setBiciclette(other.getBiciclette());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCodice()) {
          
          return false;
        }
        if (!hasNome()) {
          
          return false;
        }
        if (!hasIndirizzo()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasStato()) {
          
          return false;
        }
        if (!hasPosti()) {
          
          return false;
        }
        if (!hasBiciclette()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              codice_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nome_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              indirizzo_ = input.readBytes();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              latitude_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              longitude_ = input.readDouble();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              stato_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              posti_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              biciclette_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string codice = 1;
      private java.lang.Object codice_ = "";
      public boolean hasCodice() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getCodice() {
        java.lang.Object ref = codice_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          codice_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCodice(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        codice_ = value;
        onChanged();
        return this;
      }
      public Builder clearCodice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        codice_ = getDefaultInstance().getCodice();
        onChanged();
        return this;
      }
      void setCodice(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        codice_ = value;
        onChanged();
      }
      
      // required string nome = 2;
      private java.lang.Object nome_ = "";
      public boolean hasNome() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNome(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nome_ = value;
        onChanged();
        return this;
      }
      public Builder clearNome() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      void setNome(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        nome_ = value;
        onChanged();
      }
      
      // required string indirizzo = 3;
      private java.lang.Object indirizzo_ = "";
      public boolean hasIndirizzo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getIndirizzo() {
        java.lang.Object ref = indirizzo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          indirizzo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIndirizzo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        indirizzo_ = value;
        onChanged();
        return this;
      }
      public Builder clearIndirizzo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        indirizzo_ = getDefaultInstance().getIndirizzo();
        onChanged();
        return this;
      }
      void setIndirizzo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        indirizzo_ = value;
        onChanged();
      }
      
      // required double latitude = 4;
      private double latitude_ ;
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getLatitude() {
        return latitude_;
      }
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000008;
        latitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        latitude_ = 0D;
        onChanged();
        return this;
      }
      
      // required double longitude = 5;
      private double longitude_ ;
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public double getLongitude() {
        return longitude_;
      }
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000010;
        longitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000010);
        longitude_ = 0D;
        onChanged();
        return this;
      }
      
      // required string stato = 6;
      private java.lang.Object stato_ = "";
      public boolean hasStato() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getStato() {
        java.lang.Object ref = stato_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          stato_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStato(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        stato_ = value;
        onChanged();
        return this;
      }
      public Builder clearStato() {
        bitField0_ = (bitField0_ & ~0x00000020);
        stato_ = getDefaultInstance().getStato();
        onChanged();
        return this;
      }
      void setStato(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        stato_ = value;
        onChanged();
      }
      
      // required int32 posti = 7;
      private int posti_ ;
      public boolean hasPosti() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getPosti() {
        return posti_;
      }
      public Builder setPosti(int value) {
        bitField0_ |= 0x00000040;
        posti_ = value;
        onChanged();
        return this;
      }
      public Builder clearPosti() {
        bitField0_ = (bitField0_ & ~0x00000040);
        posti_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 biciclette = 8;
      private int biciclette_ ;
      public boolean hasBiciclette() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getBiciclette() {
        return biciclette_;
      }
      public Builder setBiciclette(int value) {
        bitField0_ |= 0x00000080;
        biciclette_ = value;
        onChanged();
        return this;
      }
      public Builder clearBiciclette() {
        bitField0_ = (bitField0_ & ~0x00000080);
        biciclette_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.tobike.data.message.Stazione)
    }
    
    static {
      defaultInstance = new Stazione(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.tobike.data.message.Stazione)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_tobike_data_message_Stazione_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_tobike_data_message_Stazione_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014tobike.proto\0225eu.trentorise.smartcampu" +
      "s.service.tobike.data.message\"\222\001\n\010Stazio" +
      "ne\022\016\n\006codice\030\001 \002(\t\022\014\n\004nome\030\002 \002(\t\022\021\n\tindi" +
      "rizzo\030\003 \002(\t\022\020\n\010latitude\030\004 \002(\001\022\021\n\tlongitu" +
      "de\030\005 \002(\001\022\r\n\005stato\030\006 \002(\t\022\r\n\005posti\030\007 \002(\005\022\022" +
      "\n\nbiciclette\030\010 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_trentorise_smartcampus_service_tobike_data_message_Stazione_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_trentorise_smartcampus_service_tobike_data_message_Stazione_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_tobike_data_message_Stazione_descriptor,
              new java.lang.String[] { "Codice", "Nome", "Indirizzo", "Latitude", "Longitude", "Stato", "Posti", "Biciclette", },
              eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione.class,
              eu.trentorise.smartcampus.service.tobike.data.message.Tobike.Stazione.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
