// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trentomale.proto

package smartcampus.service.trentomale.data.message;

public final class Trentomale {
  private Trentomale() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // repeated .smartcampus.service.trentomale.data.message.Train train = 2;
    java.util.List<smartcampus.service.trentomale.data.message.Trentomale.Train> 
        getTrainList();
    smartcampus.service.trentomale.data.message.Trentomale.Train getTrain(int index);
    int getTrainCount();
    java.util.List<? extends smartcampus.service.trentomale.data.message.Trentomale.TrainOrBuilder> 
        getTrainOrBuilderList();
    smartcampus.service.trentomale.data.message.Trentomale.TrainOrBuilder getTrainOrBuilder(
        int index);
    
    // optional .it.sayservice.platform.core.message.POI poi = 3;
    boolean hasPoi();
    it.sayservice.platform.core.message.Core.POI getPoi();
    it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder();
  }
  public static final class Station extends
      com.google.protobuf.GeneratedMessage
      implements StationOrBuilder {
    // Use Station.newBuilder() to construct.
    private Station(Builder builder) {
      super(builder);
    }
    private Station(boolean noInit) {}
    
    private static final Station defaultInstance;
    public static Station getDefaultInstance() {
      return defaultInstance;
    }
    
    public Station getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartcampus.service.trentomale.data.message.Trentomale.internal_static_smartcampus_service_trentomale_data_message_Station_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartcampus.service.trentomale.data.message.Trentomale.internal_static_smartcampus_service_trentomale_data_message_Station_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .smartcampus.service.trentomale.data.message.Train train = 2;
    public static final int TRAIN_FIELD_NUMBER = 2;
    private java.util.List<smartcampus.service.trentomale.data.message.Trentomale.Train> train_;
    public java.util.List<smartcampus.service.trentomale.data.message.Trentomale.Train> getTrainList() {
      return train_;
    }
    public java.util.List<? extends smartcampus.service.trentomale.data.message.Trentomale.TrainOrBuilder> 
        getTrainOrBuilderList() {
      return train_;
    }
    public int getTrainCount() {
      return train_.size();
    }
    public smartcampus.service.trentomale.data.message.Trentomale.Train getTrain(int index) {
      return train_.get(index);
    }
    public smartcampus.service.trentomale.data.message.Trentomale.TrainOrBuilder getTrainOrBuilder(
        int index) {
      return train_.get(index);
    }
    
    // optional .it.sayservice.platform.core.message.POI poi = 3;
    public static final int POI_FIELD_NUMBER = 3;
    private it.sayservice.platform.core.message.Core.POI poi_;
    public boolean hasPoi() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public it.sayservice.platform.core.message.Core.POI getPoi() {
      return poi_;
    }
    public it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder() {
      return poi_;
    }
    
    private void initFields() {
      name_ = "";
      train_ = java.util.Collections.emptyList();
      poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTrainCount(); i++) {
        if (!getTrain(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasPoi()) {
        if (!getPoi().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < train_.size(); i++) {
        output.writeMessage(2, train_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, poi_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < train_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, train_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, poi_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static smartcampus.service.trentomale.data.message.Trentomale.Station parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Station parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Station parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Station parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Station parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Station parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Station parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Station parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Station parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Station parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(smartcampus.service.trentomale.data.message.Trentomale.Station prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements smartcampus.service.trentomale.data.message.Trentomale.StationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartcampus.service.trentomale.data.message.Trentomale.internal_static_smartcampus_service_trentomale_data_message_Station_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartcampus.service.trentomale.data.message.Trentomale.internal_static_smartcampus_service_trentomale_data_message_Station_fieldAccessorTable;
      }
      
      // Construct using smartcampus.service.trentomale.data.message.Trentomale.Station.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTrainFieldBuilder();
          getPoiFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (trainBuilder_ == null) {
          train_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          trainBuilder_.clear();
        }
        if (poiBuilder_ == null) {
          poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
        } else {
          poiBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartcampus.service.trentomale.data.message.Trentomale.Station.getDescriptor();
      }
      
      public smartcampus.service.trentomale.data.message.Trentomale.Station getDefaultInstanceForType() {
        return smartcampus.service.trentomale.data.message.Trentomale.Station.getDefaultInstance();
      }
      
      public smartcampus.service.trentomale.data.message.Trentomale.Station build() {
        smartcampus.service.trentomale.data.message.Trentomale.Station result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private smartcampus.service.trentomale.data.message.Trentomale.Station buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        smartcampus.service.trentomale.data.message.Trentomale.Station result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public smartcampus.service.trentomale.data.message.Trentomale.Station buildPartial() {
        smartcampus.service.trentomale.data.message.Trentomale.Station result = new smartcampus.service.trentomale.data.message.Trentomale.Station(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (trainBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            train_ = java.util.Collections.unmodifiableList(train_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.train_ = train_;
        } else {
          result.train_ = trainBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (poiBuilder_ == null) {
          result.poi_ = poi_;
        } else {
          result.poi_ = poiBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartcampus.service.trentomale.data.message.Trentomale.Station) {
          return mergeFrom((smartcampus.service.trentomale.data.message.Trentomale.Station)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(smartcampus.service.trentomale.data.message.Trentomale.Station other) {
        if (other == smartcampus.service.trentomale.data.message.Trentomale.Station.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (trainBuilder_ == null) {
          if (!other.train_.isEmpty()) {
            if (train_.isEmpty()) {
              train_ = other.train_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTrainIsMutable();
              train_.addAll(other.train_);
            }
            onChanged();
          }
        } else {
          if (!other.train_.isEmpty()) {
            if (trainBuilder_.isEmpty()) {
              trainBuilder_.dispose();
              trainBuilder_ = null;
              train_ = other.train_;
              bitField0_ = (bitField0_ & ~0x00000002);
              trainBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTrainFieldBuilder() : null;
            } else {
              trainBuilder_.addAllMessages(other.train_);
            }
          }
        }
        if (other.hasPoi()) {
          mergePoi(other.getPoi());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getTrainCount(); i++) {
          if (!getTrain(i).isInitialized()) {
            
            return false;
          }
        }
        if (hasPoi()) {
          if (!getPoi().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              smartcampus.service.trentomale.data.message.Trentomale.Train.Builder subBuilder = smartcampus.service.trentomale.data.message.Trentomale.Train.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTrain(subBuilder.buildPartial());
              break;
            }
            case 26: {
              it.sayservice.platform.core.message.Core.POI.Builder subBuilder = it.sayservice.platform.core.message.Core.POI.newBuilder();
              if (hasPoi()) {
                subBuilder.mergeFrom(getPoi());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPoi(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // repeated .smartcampus.service.trentomale.data.message.Train train = 2;
      private java.util.List<smartcampus.service.trentomale.data.message.Trentomale.Train> train_ =
        java.util.Collections.emptyList();
      private void ensureTrainIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          train_ = new java.util.ArrayList<smartcampus.service.trentomale.data.message.Trentomale.Train>(train_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          smartcampus.service.trentomale.data.message.Trentomale.Train, smartcampus.service.trentomale.data.message.Trentomale.Train.Builder, smartcampus.service.trentomale.data.message.Trentomale.TrainOrBuilder> trainBuilder_;
      
      public java.util.List<smartcampus.service.trentomale.data.message.Trentomale.Train> getTrainList() {
        if (trainBuilder_ == null) {
          return java.util.Collections.unmodifiableList(train_);
        } else {
          return trainBuilder_.getMessageList();
        }
      }
      public int getTrainCount() {
        if (trainBuilder_ == null) {
          return train_.size();
        } else {
          return trainBuilder_.getCount();
        }
      }
      public smartcampus.service.trentomale.data.message.Trentomale.Train getTrain(int index) {
        if (trainBuilder_ == null) {
          return train_.get(index);
        } else {
          return trainBuilder_.getMessage(index);
        }
      }
      public Builder setTrain(
          int index, smartcampus.service.trentomale.data.message.Trentomale.Train value) {
        if (trainBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTrainIsMutable();
          train_.set(index, value);
          onChanged();
        } else {
          trainBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTrain(
          int index, smartcampus.service.trentomale.data.message.Trentomale.Train.Builder builderForValue) {
        if (trainBuilder_ == null) {
          ensureTrainIsMutable();
          train_.set(index, builderForValue.build());
          onChanged();
        } else {
          trainBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTrain(smartcampus.service.trentomale.data.message.Trentomale.Train value) {
        if (trainBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTrainIsMutable();
          train_.add(value);
          onChanged();
        } else {
          trainBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTrain(
          int index, smartcampus.service.trentomale.data.message.Trentomale.Train value) {
        if (trainBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTrainIsMutable();
          train_.add(index, value);
          onChanged();
        } else {
          trainBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTrain(
          smartcampus.service.trentomale.data.message.Trentomale.Train.Builder builderForValue) {
        if (trainBuilder_ == null) {
          ensureTrainIsMutable();
          train_.add(builderForValue.build());
          onChanged();
        } else {
          trainBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTrain(
          int index, smartcampus.service.trentomale.data.message.Trentomale.Train.Builder builderForValue) {
        if (trainBuilder_ == null) {
          ensureTrainIsMutable();
          train_.add(index, builderForValue.build());
          onChanged();
        } else {
          trainBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTrain(
          java.lang.Iterable<? extends smartcampus.service.trentomale.data.message.Trentomale.Train> values) {
        if (trainBuilder_ == null) {
          ensureTrainIsMutable();
          super.addAll(values, train_);
          onChanged();
        } else {
          trainBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTrain() {
        if (trainBuilder_ == null) {
          train_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          trainBuilder_.clear();
        }
        return this;
      }
      public Builder removeTrain(int index) {
        if (trainBuilder_ == null) {
          ensureTrainIsMutable();
          train_.remove(index);
          onChanged();
        } else {
          trainBuilder_.remove(index);
        }
        return this;
      }
      public smartcampus.service.trentomale.data.message.Trentomale.Train.Builder getTrainBuilder(
          int index) {
        return getTrainFieldBuilder().getBuilder(index);
      }
      public smartcampus.service.trentomale.data.message.Trentomale.TrainOrBuilder getTrainOrBuilder(
          int index) {
        if (trainBuilder_ == null) {
          return train_.get(index);  } else {
          return trainBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends smartcampus.service.trentomale.data.message.Trentomale.TrainOrBuilder> 
           getTrainOrBuilderList() {
        if (trainBuilder_ != null) {
          return trainBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(train_);
        }
      }
      public smartcampus.service.trentomale.data.message.Trentomale.Train.Builder addTrainBuilder() {
        return getTrainFieldBuilder().addBuilder(
            smartcampus.service.trentomale.data.message.Trentomale.Train.getDefaultInstance());
      }
      public smartcampus.service.trentomale.data.message.Trentomale.Train.Builder addTrainBuilder(
          int index) {
        return getTrainFieldBuilder().addBuilder(
            index, smartcampus.service.trentomale.data.message.Trentomale.Train.getDefaultInstance());
      }
      public java.util.List<smartcampus.service.trentomale.data.message.Trentomale.Train.Builder> 
           getTrainBuilderList() {
        return getTrainFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          smartcampus.service.trentomale.data.message.Trentomale.Train, smartcampus.service.trentomale.data.message.Trentomale.Train.Builder, smartcampus.service.trentomale.data.message.Trentomale.TrainOrBuilder> 
          getTrainFieldBuilder() {
        if (trainBuilder_ == null) {
          trainBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              smartcampus.service.trentomale.data.message.Trentomale.Train, smartcampus.service.trentomale.data.message.Trentomale.Train.Builder, smartcampus.service.trentomale.data.message.Trentomale.TrainOrBuilder>(
                  train_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          train_ = null;
        }
        return trainBuilder_;
      }
      
      // optional .it.sayservice.platform.core.message.POI poi = 3;
      private it.sayservice.platform.core.message.Core.POI poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder> poiBuilder_;
      public boolean hasPoi() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public it.sayservice.platform.core.message.Core.POI getPoi() {
        if (poiBuilder_ == null) {
          return poi_;
        } else {
          return poiBuilder_.getMessage();
        }
      }
      public Builder setPoi(it.sayservice.platform.core.message.Core.POI value) {
        if (poiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          poi_ = value;
          onChanged();
        } else {
          poiBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setPoi(
          it.sayservice.platform.core.message.Core.POI.Builder builderForValue) {
        if (poiBuilder_ == null) {
          poi_ = builderForValue.build();
          onChanged();
        } else {
          poiBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergePoi(it.sayservice.platform.core.message.Core.POI value) {
        if (poiBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              poi_ != it.sayservice.platform.core.message.Core.POI.getDefaultInstance()) {
            poi_ =
              it.sayservice.platform.core.message.Core.POI.newBuilder(poi_).mergeFrom(value).buildPartial();
          } else {
            poi_ = value;
          }
          onChanged();
        } else {
          poiBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearPoi() {
        if (poiBuilder_ == null) {
          poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
          onChanged();
        } else {
          poiBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public it.sayservice.platform.core.message.Core.POI.Builder getPoiBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getPoiFieldBuilder().getBuilder();
      }
      public it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder() {
        if (poiBuilder_ != null) {
          return poiBuilder_.getMessageOrBuilder();
        } else {
          return poi_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder> 
          getPoiFieldBuilder() {
        if (poiBuilder_ == null) {
          poiBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder>(
                  poi_,
                  getParentForChildren(),
                  isClean());
          poi_ = null;
        }
        return poiBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:smartcampus.service.trentomale.data.message.Station)
    }
    
    static {
      defaultInstance = new Station(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:smartcampus.service.trentomale.data.message.Station)
  }
  
  public interface TrainOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required int32 number = 2;
    boolean hasNumber();
    int getNumber();
    
    // optional string time = 3;
    boolean hasTime();
    String getTime();
    
    // optional string direction = 4;
    boolean hasDirection();
    String getDirection();
    
    // required int32 delay = 5;
    boolean hasDelay();
    int getDelay();
    
    // required string station = 6;
    boolean hasStation();
    String getStation();
  }
  public static final class Train extends
      com.google.protobuf.GeneratedMessage
      implements TrainOrBuilder {
    // Use Train.newBuilder() to construct.
    private Train(Builder builder) {
      super(builder);
    }
    private Train(boolean noInit) {}
    
    private static final Train defaultInstance;
    public static Train getDefaultInstance() {
      return defaultInstance;
    }
    
    public Train getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartcampus.service.trentomale.data.message.Trentomale.internal_static_smartcampus_service_trentomale_data_message_Train_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartcampus.service.trentomale.data.message.Trentomale.internal_static_smartcampus_service_trentomale_data_message_Train_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required int32 number = 2;
    public static final int NUMBER_FIELD_NUMBER = 2;
    private int number_;
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getNumber() {
      return number_;
    }
    
    // optional string time = 3;
    public static final int TIME_FIELD_NUMBER = 3;
    private java.lang.Object time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          time_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string direction = 4;
    public static final int DIRECTION_FIELD_NUMBER = 4;
    private java.lang.Object direction_;
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          direction_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 delay = 5;
    public static final int DELAY_FIELD_NUMBER = 5;
    private int delay_;
    public boolean hasDelay() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getDelay() {
      return delay_;
    }
    
    // required string station = 6;
    public static final int STATION_FIELD_NUMBER = 6;
    private java.lang.Object station_;
    public boolean hasStation() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getStation() {
      java.lang.Object ref = station_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          station_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStationBytes() {
      java.lang.Object ref = station_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        station_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0;
      number_ = 0;
      time_ = "";
      direction_ = "";
      delay_ = 0;
      station_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDelay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, number_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDirectionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, delay_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getStationBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, number_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDirectionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, delay_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getStationBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static smartcampus.service.trentomale.data.message.Trentomale.Train parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Train parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Train parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Train parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Train parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Train parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Train parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Train parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Train parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smartcampus.service.trentomale.data.message.Trentomale.Train parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(smartcampus.service.trentomale.data.message.Trentomale.Train prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements smartcampus.service.trentomale.data.message.Trentomale.TrainOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartcampus.service.trentomale.data.message.Trentomale.internal_static_smartcampus_service_trentomale_data_message_Train_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartcampus.service.trentomale.data.message.Trentomale.internal_static_smartcampus_service_trentomale_data_message_Train_fieldAccessorTable;
      }
      
      // Construct using smartcampus.service.trentomale.data.message.Trentomale.Train.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        direction_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        delay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        station_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartcampus.service.trentomale.data.message.Trentomale.Train.getDescriptor();
      }
      
      public smartcampus.service.trentomale.data.message.Trentomale.Train getDefaultInstanceForType() {
        return smartcampus.service.trentomale.data.message.Trentomale.Train.getDefaultInstance();
      }
      
      public smartcampus.service.trentomale.data.message.Trentomale.Train build() {
        smartcampus.service.trentomale.data.message.Trentomale.Train result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private smartcampus.service.trentomale.data.message.Trentomale.Train buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        smartcampus.service.trentomale.data.message.Trentomale.Train result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public smartcampus.service.trentomale.data.message.Trentomale.Train buildPartial() {
        smartcampus.service.trentomale.data.message.Trentomale.Train result = new smartcampus.service.trentomale.data.message.Trentomale.Train(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.direction_ = direction_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.delay_ = delay_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.station_ = station_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartcampus.service.trentomale.data.message.Trentomale.Train) {
          return mergeFrom((smartcampus.service.trentomale.data.message.Trentomale.Train)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(smartcampus.service.trentomale.data.message.Trentomale.Train other) {
        if (other == smartcampus.service.trentomale.data.message.Trentomale.Train.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasNumber()) {
          setNumber(other.getNumber());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasDirection()) {
          setDirection(other.getDirection());
        }
        if (other.hasDelay()) {
          setDelay(other.getDelay());
        }
        if (other.hasStation()) {
          setStation(other.getStation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasNumber()) {
          
          return false;
        }
        if (!hasDelay()) {
          
          return false;
        }
        if (!hasStation()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              number_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              time_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              direction_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              delay_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              station_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 number = 2;
      private int number_ ;
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getNumber() {
        return number_;
      }
      public Builder setNumber(int value) {
        bitField0_ |= 0x00000002;
        number_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        number_ = 0;
        onChanged();
        return this;
      }
      
      // optional string time = 3;
      private java.lang.Object time_ = "";
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      void setTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
      }
      
      // optional string direction = 4;
      private java.lang.Object direction_ = "";
      public boolean hasDirection() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDirection(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        direction_ = value;
        onChanged();
        return this;
      }
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000008);
        direction_ = getDefaultInstance().getDirection();
        onChanged();
        return this;
      }
      void setDirection(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        direction_ = value;
        onChanged();
      }
      
      // required int32 delay = 5;
      private int delay_ ;
      public boolean hasDelay() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getDelay() {
        return delay_;
      }
      public Builder setDelay(int value) {
        bitField0_ |= 0x00000010;
        delay_ = value;
        onChanged();
        return this;
      }
      public Builder clearDelay() {
        bitField0_ = (bitField0_ & ~0x00000010);
        delay_ = 0;
        onChanged();
        return this;
      }
      
      // required string station = 6;
      private java.lang.Object station_ = "";
      public boolean hasStation() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getStation() {
        java.lang.Object ref = station_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          station_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStation(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        station_ = value;
        onChanged();
        return this;
      }
      public Builder clearStation() {
        bitField0_ = (bitField0_ & ~0x00000020);
        station_ = getDefaultInstance().getStation();
        onChanged();
        return this;
      }
      void setStation(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        station_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:smartcampus.service.trentomale.data.message.Train)
    }
    
    static {
      defaultInstance = new Train(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:smartcampus.service.trentomale.data.message.Train)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcampus_service_trentomale_data_message_Station_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_smartcampus_service_trentomale_data_message_Station_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcampus_service_trentomale_data_message_Train_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_smartcampus_service_trentomale_data_message_Train_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020trentomale.proto\022+smartcampus.service." +
      "trentomale.data.message\032\ncore.proto\"\221\001\n\007" +
      "Station\022\014\n\004name\030\001 \002(\t\022A\n\005train\030\002 \003(\01322.s" +
      "martcampus.service.trentomale.data.messa" +
      "ge.Train\0225\n\003poi\030\003 \001(\0132(.it.sayservice.pl" +
      "atform.core.message.POI\"d\n\005Train\022\n\n\002id\030\001" +
      " \002(\005\022\016\n\006number\030\002 \002(\005\022\014\n\004time\030\003 \001(\t\022\021\n\tdi" +
      "rection\030\004 \001(\t\022\r\n\005delay\030\005 \002(\005\022\017\n\007station\030" +
      "\006 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_smartcampus_service_trentomale_data_message_Station_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_smartcampus_service_trentomale_data_message_Station_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_smartcampus_service_trentomale_data_message_Station_descriptor,
              new java.lang.String[] { "Name", "Train", "Poi", },
              smartcampus.service.trentomale.data.message.Trentomale.Station.class,
              smartcampus.service.trentomale.data.message.Trentomale.Station.Builder.class);
          internal_static_smartcampus_service_trentomale_data_message_Train_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_smartcampus_service_trentomale_data_message_Train_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_smartcampus_service_trentomale_data_message_Train_descriptor,
              new java.lang.String[] { "Id", "Number", "Time", "Direction", "Delay", "Station", },
              smartcampus.service.trentomale.data.message.Trentomale.Train.class,
              smartcampus.service.trentomale.data.message.Trentomale.Train.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          it.sayservice.platform.core.message.Core.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
