// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ordinanzerovereto.proto

package eu.trentorise.smartcampus.services.ordinanzerovereto.data.message;

public final class Ordinanzerovereto {
  private Ordinanzerovereto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OrdinanzaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string ogetto = 2;
    boolean hasOgetto();
    String getOgetto();
    
    // required string data = 3;
    boolean hasData();
    String getData();
    
    // required string dal = 4;
    boolean hasDal();
    String getDal();
    
    // required string al = 5;
    boolean hasAl();
    String getAl();
    
    // required string tipologia = 6;
    boolean hasTipologia();
    String getTipologia();
    
    // optional string stato = 7;
    boolean hasStato();
    String getStato();
    
    // repeated .eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Via vie = 8;
    java.util.List<eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via> 
        getVieList();
    eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via getVie(int index);
    int getVieCount();
    java.util.List<? extends eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.ViaOrBuilder> 
        getVieOrBuilderList();
    eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.ViaOrBuilder getVieOrBuilder(
        int index);
  }
  public static final class Ordinanza extends
      com.google.protobuf.GeneratedMessage
      implements OrdinanzaOrBuilder {
    // Use Ordinanza.newBuilder() to construct.
    private Ordinanza(Builder builder) {
      super(builder);
    }
    private Ordinanza(boolean noInit) {}
    
    private static final Ordinanza defaultInstance;
    public static Ordinanza getDefaultInstance() {
      return defaultInstance;
    }
    
    public Ordinanza getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Ordinanza_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Ordinanza_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string ogetto = 2;
    public static final int OGETTO_FIELD_NUMBER = 2;
    private java.lang.Object ogetto_;
    public boolean hasOgetto() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getOgetto() {
      java.lang.Object ref = ogetto_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ogetto_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOgettoBytes() {
      java.lang.Object ref = ogetto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ogetto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private java.lang.Object data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          data_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string dal = 4;
    public static final int DAL_FIELD_NUMBER = 4;
    private java.lang.Object dal_;
    public boolean hasDal() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDal() {
      java.lang.Object ref = dal_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dal_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDalBytes() {
      java.lang.Object ref = dal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string al = 5;
    public static final int AL_FIELD_NUMBER = 5;
    private java.lang.Object al_;
    public boolean hasAl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getAl() {
      java.lang.Object ref = al_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          al_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAlBytes() {
      java.lang.Object ref = al_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        al_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string tipologia = 6;
    public static final int TIPOLOGIA_FIELD_NUMBER = 6;
    private java.lang.Object tipologia_;
    public boolean hasTipologia() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getTipologia() {
      java.lang.Object ref = tipologia_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tipologia_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTipologiaBytes() {
      java.lang.Object ref = tipologia_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tipologia_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string stato = 7;
    public static final int STATO_FIELD_NUMBER = 7;
    private java.lang.Object stato_;
    public boolean hasStato() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getStato() {
      java.lang.Object ref = stato_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          stato_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStatoBytes() {
      java.lang.Object ref = stato_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        stato_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Via vie = 8;
    public static final int VIE_FIELD_NUMBER = 8;
    private java.util.List<eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via> vie_;
    public java.util.List<eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via> getVieList() {
      return vie_;
    }
    public java.util.List<? extends eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.ViaOrBuilder> 
        getVieOrBuilderList() {
      return vie_;
    }
    public int getVieCount() {
      return vie_.size();
    }
    public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via getVie(int index) {
      return vie_.get(index);
    }
    public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.ViaOrBuilder getVieOrBuilder(
        int index) {
      return vie_.get(index);
    }
    
    private void initFields() {
      id_ = "";
      ogetto_ = "";
      data_ = "";
      dal_ = "";
      al_ = "";
      tipologia_ = "";
      stato_ = "";
      vie_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOgetto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTipologia()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getVieCount(); i++) {
        if (!getVie(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOgettoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDalBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAlBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTipologiaBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getStatoBytes());
      }
      for (int i = 0; i < vie_.size(); i++) {
        output.writeMessage(8, vie_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOgettoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDataBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDalBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAlBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTipologiaBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getStatoBytes());
      }
      for (int i = 0; i < vie_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, vie_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.OrdinanzaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Ordinanza_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Ordinanza_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getVieFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ogetto_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dal_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        al_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        tipologia_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        stato_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        if (vieBuilder_ == null) {
          vie_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          vieBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza build() {
        eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza buildPartial() {
        eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza result = new eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ogetto_ = ogetto_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dal_ = dal_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.al_ = al_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.tipologia_ = tipologia_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.stato_ = stato_;
        if (vieBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            vie_ = java.util.Collections.unmodifiableList(vie_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.vie_ = vie_;
        } else {
          result.vie_ = vieBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza) {
          return mergeFrom((eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza other) {
        if (other == eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasOgetto()) {
          setOgetto(other.getOgetto());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasDal()) {
          setDal(other.getDal());
        }
        if (other.hasAl()) {
          setAl(other.getAl());
        }
        if (other.hasTipologia()) {
          setTipologia(other.getTipologia());
        }
        if (other.hasStato()) {
          setStato(other.getStato());
        }
        if (vieBuilder_ == null) {
          if (!other.vie_.isEmpty()) {
            if (vie_.isEmpty()) {
              vie_ = other.vie_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureVieIsMutable();
              vie_.addAll(other.vie_);
            }
            onChanged();
          }
        } else {
          if (!other.vie_.isEmpty()) {
            if (vieBuilder_.isEmpty()) {
              vieBuilder_.dispose();
              vieBuilder_ = null;
              vie_ = other.vie_;
              bitField0_ = (bitField0_ & ~0x00000080);
              vieBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getVieFieldBuilder() : null;
            } else {
              vieBuilder_.addAllMessages(other.vie_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasOgetto()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        if (!hasDal()) {
          
          return false;
        }
        if (!hasAl()) {
          
          return false;
        }
        if (!hasTipologia()) {
          
          return false;
        }
        for (int i = 0; i < getVieCount(); i++) {
          if (!getVie(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              ogetto_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              dal_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              al_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              tipologia_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              stato_ = input.readBytes();
              break;
            }
            case 66: {
              eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder subBuilder = eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addVie(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string ogetto = 2;
      private java.lang.Object ogetto_ = "";
      public boolean hasOgetto() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getOgetto() {
        java.lang.Object ref = ogetto_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ogetto_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOgetto(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ogetto_ = value;
        onChanged();
        return this;
      }
      public Builder clearOgetto() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ogetto_ = getDefaultInstance().getOgetto();
        onChanged();
        return this;
      }
      void setOgetto(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        ogetto_ = value;
        onChanged();
      }
      
      // required string data = 3;
      private java.lang.Object data_ = "";
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setData(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      void setData(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
      }
      
      // required string dal = 4;
      private java.lang.Object dal_ = "";
      public boolean hasDal() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDal() {
        java.lang.Object ref = dal_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dal_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDal(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dal_ = value;
        onChanged();
        return this;
      }
      public Builder clearDal() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dal_ = getDefaultInstance().getDal();
        onChanged();
        return this;
      }
      void setDal(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        dal_ = value;
        onChanged();
      }
      
      // required string al = 5;
      private java.lang.Object al_ = "";
      public boolean hasAl() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getAl() {
        java.lang.Object ref = al_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          al_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        al_ = value;
        onChanged();
        return this;
      }
      public Builder clearAl() {
        bitField0_ = (bitField0_ & ~0x00000010);
        al_ = getDefaultInstance().getAl();
        onChanged();
        return this;
      }
      void setAl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        al_ = value;
        onChanged();
      }
      
      // required string tipologia = 6;
      private java.lang.Object tipologia_ = "";
      public boolean hasTipologia() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getTipologia() {
        java.lang.Object ref = tipologia_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tipologia_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTipologia(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        tipologia_ = value;
        onChanged();
        return this;
      }
      public Builder clearTipologia() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tipologia_ = getDefaultInstance().getTipologia();
        onChanged();
        return this;
      }
      void setTipologia(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        tipologia_ = value;
        onChanged();
      }
      
      // optional string stato = 7;
      private java.lang.Object stato_ = "";
      public boolean hasStato() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getStato() {
        java.lang.Object ref = stato_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          stato_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStato(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        stato_ = value;
        onChanged();
        return this;
      }
      public Builder clearStato() {
        bitField0_ = (bitField0_ & ~0x00000040);
        stato_ = getDefaultInstance().getStato();
        onChanged();
        return this;
      }
      void setStato(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        stato_ = value;
        onChanged();
      }
      
      // repeated .eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Via vie = 8;
      private java.util.List<eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via> vie_ =
        java.util.Collections.emptyList();
      private void ensureVieIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          vie_ = new java.util.ArrayList<eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via>(vie_);
          bitField0_ |= 0x00000080;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.ViaOrBuilder> vieBuilder_;
      
      public java.util.List<eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via> getVieList() {
        if (vieBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vie_);
        } else {
          return vieBuilder_.getMessageList();
        }
      }
      public int getVieCount() {
        if (vieBuilder_ == null) {
          return vie_.size();
        } else {
          return vieBuilder_.getCount();
        }
      }
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via getVie(int index) {
        if (vieBuilder_ == null) {
          return vie_.get(index);
        } else {
          return vieBuilder_.getMessage(index);
        }
      }
      public Builder setVie(
          int index, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via value) {
        if (vieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVieIsMutable();
          vie_.set(index, value);
          onChanged();
        } else {
          vieBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setVie(
          int index, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder builderForValue) {
        if (vieBuilder_ == null) {
          ensureVieIsMutable();
          vie_.set(index, builderForValue.build());
          onChanged();
        } else {
          vieBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addVie(eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via value) {
        if (vieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVieIsMutable();
          vie_.add(value);
          onChanged();
        } else {
          vieBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addVie(
          int index, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via value) {
        if (vieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVieIsMutable();
          vie_.add(index, value);
          onChanged();
        } else {
          vieBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addVie(
          eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder builderForValue) {
        if (vieBuilder_ == null) {
          ensureVieIsMutable();
          vie_.add(builderForValue.build());
          onChanged();
        } else {
          vieBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addVie(
          int index, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder builderForValue) {
        if (vieBuilder_ == null) {
          ensureVieIsMutable();
          vie_.add(index, builderForValue.build());
          onChanged();
        } else {
          vieBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllVie(
          java.lang.Iterable<? extends eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via> values) {
        if (vieBuilder_ == null) {
          ensureVieIsMutable();
          super.addAll(values, vie_);
          onChanged();
        } else {
          vieBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearVie() {
        if (vieBuilder_ == null) {
          vie_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          vieBuilder_.clear();
        }
        return this;
      }
      public Builder removeVie(int index) {
        if (vieBuilder_ == null) {
          ensureVieIsMutable();
          vie_.remove(index);
          onChanged();
        } else {
          vieBuilder_.remove(index);
        }
        return this;
      }
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder getVieBuilder(
          int index) {
        return getVieFieldBuilder().getBuilder(index);
      }
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.ViaOrBuilder getVieOrBuilder(
          int index) {
        if (vieBuilder_ == null) {
          return vie_.get(index);  } else {
          return vieBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.ViaOrBuilder> 
           getVieOrBuilderList() {
        if (vieBuilder_ != null) {
          return vieBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vie_);
        }
      }
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder addVieBuilder() {
        return getVieFieldBuilder().addBuilder(
            eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.getDefaultInstance());
      }
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder addVieBuilder(
          int index) {
        return getVieFieldBuilder().addBuilder(
            index, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.getDefaultInstance());
      }
      public java.util.List<eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder> 
           getVieBuilderList() {
        return getVieFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.ViaOrBuilder> 
          getVieFieldBuilder() {
        if (vieBuilder_ == null) {
          vieBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder, eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.ViaOrBuilder>(
                  vie_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          vie_ = null;
        }
        return vieBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanza)
    }
    
    static {
      defaultInstance = new Ordinanza(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanza)
  }
  
  public interface ViaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string codice_via = 1;
    boolean hasCodiceVia();
    String getCodiceVia();
    
    // required string descrizione_via = 2;
    boolean hasDescrizioneVia();
    String getDescrizioneVia();
    
    // optional string note = 3;
    boolean hasNote();
    String getNote();
    
    // required double lat = 4;
    boolean hasLat();
    double getLat();
    
    // required double lng = 5;
    boolean hasLng();
    double getLng();
    
    // optional string dal_civico = 6;
    boolean hasDalCivico();
    String getDalCivico();
    
    // optional string al_civico = 7;
    boolean hasAlCivico();
    String getAlCivico();
    
    // optional string dal_intersezione = 8;
    boolean hasDalIntersezione();
    String getDalIntersezione();
    
    // optional string al_intersezione = 9;
    boolean hasAlIntersezione();
    String getAlIntersezione();
    
    // optional string tipologia = 10;
    boolean hasTipologia();
    String getTipologia();
  }
  public static final class Via extends
      com.google.protobuf.GeneratedMessage
      implements ViaOrBuilder {
    // Use Via.newBuilder() to construct.
    private Via(Builder builder) {
      super(builder);
    }
    private Via(boolean noInit) {}
    
    private static final Via defaultInstance;
    public static Via getDefaultInstance() {
      return defaultInstance;
    }
    
    public Via getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Via_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Via_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string codice_via = 1;
    public static final int CODICE_VIA_FIELD_NUMBER = 1;
    private java.lang.Object codiceVia_;
    public boolean hasCodiceVia() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getCodiceVia() {
      java.lang.Object ref = codiceVia_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          codiceVia_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCodiceViaBytes() {
      java.lang.Object ref = codiceVia_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        codiceVia_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string descrizione_via = 2;
    public static final int DESCRIZIONE_VIA_FIELD_NUMBER = 2;
    private java.lang.Object descrizioneVia_;
    public boolean hasDescrizioneVia() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDescrizioneVia() {
      java.lang.Object ref = descrizioneVia_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          descrizioneVia_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescrizioneViaBytes() {
      java.lang.Object ref = descrizioneVia_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        descrizioneVia_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string note = 3;
    public static final int NOTE_FIELD_NUMBER = 3;
    private java.lang.Object note_;
    public boolean hasNote() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getNote() {
      java.lang.Object ref = note_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          note_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNoteBytes() {
      java.lang.Object ref = note_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        note_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required double lat = 4;
    public static final int LAT_FIELD_NUMBER = 4;
    private double lat_;
    public boolean hasLat() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getLat() {
      return lat_;
    }
    
    // required double lng = 5;
    public static final int LNG_FIELD_NUMBER = 5;
    private double lng_;
    public boolean hasLng() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public double getLng() {
      return lng_;
    }
    
    // optional string dal_civico = 6;
    public static final int DAL_CIVICO_FIELD_NUMBER = 6;
    private java.lang.Object dalCivico_;
    public boolean hasDalCivico() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getDalCivico() {
      java.lang.Object ref = dalCivico_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dalCivico_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDalCivicoBytes() {
      java.lang.Object ref = dalCivico_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dalCivico_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string al_civico = 7;
    public static final int AL_CIVICO_FIELD_NUMBER = 7;
    private java.lang.Object alCivico_;
    public boolean hasAlCivico() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getAlCivico() {
      java.lang.Object ref = alCivico_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          alCivico_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAlCivicoBytes() {
      java.lang.Object ref = alCivico_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        alCivico_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string dal_intersezione = 8;
    public static final int DAL_INTERSEZIONE_FIELD_NUMBER = 8;
    private java.lang.Object dalIntersezione_;
    public boolean hasDalIntersezione() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getDalIntersezione() {
      java.lang.Object ref = dalIntersezione_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dalIntersezione_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDalIntersezioneBytes() {
      java.lang.Object ref = dalIntersezione_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dalIntersezione_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string al_intersezione = 9;
    public static final int AL_INTERSEZIONE_FIELD_NUMBER = 9;
    private java.lang.Object alIntersezione_;
    public boolean hasAlIntersezione() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getAlIntersezione() {
      java.lang.Object ref = alIntersezione_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          alIntersezione_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAlIntersezioneBytes() {
      java.lang.Object ref = alIntersezione_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        alIntersezione_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string tipologia = 10;
    public static final int TIPOLOGIA_FIELD_NUMBER = 10;
    private java.lang.Object tipologia_;
    public boolean hasTipologia() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getTipologia() {
      java.lang.Object ref = tipologia_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tipologia_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTipologiaBytes() {
      java.lang.Object ref = tipologia_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tipologia_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      codiceVia_ = "";
      descrizioneVia_ = "";
      note_ = "";
      lat_ = 0D;
      lng_ = 0D;
      dalCivico_ = "";
      alCivico_ = "";
      dalIntersezione_ = "";
      alIntersezione_ = "";
      tipologia_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCodiceVia()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescrizioneVia()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCodiceViaBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescrizioneViaBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNoteBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, lat_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, lng_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDalCivicoBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getAlCivicoBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getDalIntersezioneBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getAlIntersezioneBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getTipologiaBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCodiceViaBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescrizioneViaBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNoteBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, lat_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, lng_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDalCivicoBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getAlCivicoBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getDalIntersezioneBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getAlIntersezioneBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getTipologiaBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.ViaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Via_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Via_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        codiceVia_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        descrizioneVia_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        note_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        lng_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        dalCivico_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        alCivico_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        dalIntersezione_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        alIntersezione_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        tipologia_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via build() {
        eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via buildPartial() {
        eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via result = new eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.codiceVia_ = codiceVia_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.descrizioneVia_ = descrizioneVia_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.note_ = note_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lng_ = lng_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.dalCivico_ = dalCivico_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.alCivico_ = alCivico_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.dalIntersezione_ = dalIntersezione_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.alIntersezione_ = alIntersezione_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.tipologia_ = tipologia_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via) {
          return mergeFrom((eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via other) {
        if (other == eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.getDefaultInstance()) return this;
        if (other.hasCodiceVia()) {
          setCodiceVia(other.getCodiceVia());
        }
        if (other.hasDescrizioneVia()) {
          setDescrizioneVia(other.getDescrizioneVia());
        }
        if (other.hasNote()) {
          setNote(other.getNote());
        }
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLng()) {
          setLng(other.getLng());
        }
        if (other.hasDalCivico()) {
          setDalCivico(other.getDalCivico());
        }
        if (other.hasAlCivico()) {
          setAlCivico(other.getAlCivico());
        }
        if (other.hasDalIntersezione()) {
          setDalIntersezione(other.getDalIntersezione());
        }
        if (other.hasAlIntersezione()) {
          setAlIntersezione(other.getAlIntersezione());
        }
        if (other.hasTipologia()) {
          setTipologia(other.getTipologia());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCodiceVia()) {
          
          return false;
        }
        if (!hasDescrizioneVia()) {
          
          return false;
        }
        if (!hasLat()) {
          
          return false;
        }
        if (!hasLng()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              codiceVia_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              descrizioneVia_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              note_ = input.readBytes();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              lat_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              lng_ = input.readDouble();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              dalCivico_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              alCivico_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              dalIntersezione_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              alIntersezione_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              tipologia_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string codice_via = 1;
      private java.lang.Object codiceVia_ = "";
      public boolean hasCodiceVia() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getCodiceVia() {
        java.lang.Object ref = codiceVia_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          codiceVia_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCodiceVia(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        codiceVia_ = value;
        onChanged();
        return this;
      }
      public Builder clearCodiceVia() {
        bitField0_ = (bitField0_ & ~0x00000001);
        codiceVia_ = getDefaultInstance().getCodiceVia();
        onChanged();
        return this;
      }
      void setCodiceVia(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        codiceVia_ = value;
        onChanged();
      }
      
      // required string descrizione_via = 2;
      private java.lang.Object descrizioneVia_ = "";
      public boolean hasDescrizioneVia() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDescrizioneVia() {
        java.lang.Object ref = descrizioneVia_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          descrizioneVia_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescrizioneVia(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        descrizioneVia_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescrizioneVia() {
        bitField0_ = (bitField0_ & ~0x00000002);
        descrizioneVia_ = getDefaultInstance().getDescrizioneVia();
        onChanged();
        return this;
      }
      void setDescrizioneVia(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        descrizioneVia_ = value;
        onChanged();
      }
      
      // optional string note = 3;
      private java.lang.Object note_ = "";
      public boolean hasNote() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getNote() {
        java.lang.Object ref = note_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          note_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNote(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        note_ = value;
        onChanged();
        return this;
      }
      public Builder clearNote() {
        bitField0_ = (bitField0_ & ~0x00000004);
        note_ = getDefaultInstance().getNote();
        onChanged();
        return this;
      }
      void setNote(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        note_ = value;
        onChanged();
      }
      
      // required double lat = 4;
      private double lat_ ;
      public boolean hasLat() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getLat() {
        return lat_;
      }
      public Builder setLat(double value) {
        bitField0_ |= 0x00000008;
        lat_ = value;
        onChanged();
        return this;
      }
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lat_ = 0D;
        onChanged();
        return this;
      }
      
      // required double lng = 5;
      private double lng_ ;
      public boolean hasLng() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public double getLng() {
        return lng_;
      }
      public Builder setLng(double value) {
        bitField0_ |= 0x00000010;
        lng_ = value;
        onChanged();
        return this;
      }
      public Builder clearLng() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lng_ = 0D;
        onChanged();
        return this;
      }
      
      // optional string dal_civico = 6;
      private java.lang.Object dalCivico_ = "";
      public boolean hasDalCivico() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getDalCivico() {
        java.lang.Object ref = dalCivico_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dalCivico_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDalCivico(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        dalCivico_ = value;
        onChanged();
        return this;
      }
      public Builder clearDalCivico() {
        bitField0_ = (bitField0_ & ~0x00000020);
        dalCivico_ = getDefaultInstance().getDalCivico();
        onChanged();
        return this;
      }
      void setDalCivico(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        dalCivico_ = value;
        onChanged();
      }
      
      // optional string al_civico = 7;
      private java.lang.Object alCivico_ = "";
      public boolean hasAlCivico() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getAlCivico() {
        java.lang.Object ref = alCivico_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          alCivico_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAlCivico(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        alCivico_ = value;
        onChanged();
        return this;
      }
      public Builder clearAlCivico() {
        bitField0_ = (bitField0_ & ~0x00000040);
        alCivico_ = getDefaultInstance().getAlCivico();
        onChanged();
        return this;
      }
      void setAlCivico(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        alCivico_ = value;
        onChanged();
      }
      
      // optional string dal_intersezione = 8;
      private java.lang.Object dalIntersezione_ = "";
      public boolean hasDalIntersezione() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getDalIntersezione() {
        java.lang.Object ref = dalIntersezione_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dalIntersezione_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDalIntersezione(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        dalIntersezione_ = value;
        onChanged();
        return this;
      }
      public Builder clearDalIntersezione() {
        bitField0_ = (bitField0_ & ~0x00000080);
        dalIntersezione_ = getDefaultInstance().getDalIntersezione();
        onChanged();
        return this;
      }
      void setDalIntersezione(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        dalIntersezione_ = value;
        onChanged();
      }
      
      // optional string al_intersezione = 9;
      private java.lang.Object alIntersezione_ = "";
      public boolean hasAlIntersezione() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getAlIntersezione() {
        java.lang.Object ref = alIntersezione_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          alIntersezione_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAlIntersezione(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        alIntersezione_ = value;
        onChanged();
        return this;
      }
      public Builder clearAlIntersezione() {
        bitField0_ = (bitField0_ & ~0x00000100);
        alIntersezione_ = getDefaultInstance().getAlIntersezione();
        onChanged();
        return this;
      }
      void setAlIntersezione(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        alIntersezione_ = value;
        onChanged();
      }
      
      // optional string tipologia = 10;
      private java.lang.Object tipologia_ = "";
      public boolean hasTipologia() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getTipologia() {
        java.lang.Object ref = tipologia_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tipologia_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTipologia(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        tipologia_ = value;
        onChanged();
        return this;
      }
      public Builder clearTipologia() {
        bitField0_ = (bitField0_ & ~0x00000200);
        tipologia_ = getDefaultInstance().getTipologia();
        onChanged();
        return this;
      }
      void setTipologia(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        tipologia_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Via)
    }
    
    static {
      defaultInstance = new Via(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Via)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Ordinanza_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Ordinanza_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Via_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Via_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ordinanzerovereto.proto\022Aeu.trentorise" +
      ".smartcampus.services.ordinanzerovereto." +
      "data.message\"\305\001\n\tOrdinanza\022\n\n\002id\030\001 \002(\t\022\016" +
      "\n\006ogetto\030\002 \002(\t\022\014\n\004data\030\003 \002(\t\022\013\n\003dal\030\004 \002(" +
      "\t\022\n\n\002al\030\005 \002(\t\022\021\n\ttipologia\030\006 \002(\t\022\r\n\005stat" +
      "o\030\007 \001(\t\022S\n\003vie\030\010 \003(\0132F.eu.trentorise.sma" +
      "rtcampus.services.ordinanzerovereto.data" +
      ".message.Via\"\307\001\n\003Via\022\022\n\ncodice_via\030\001 \002(\t" +
      "\022\027\n\017descrizione_via\030\002 \002(\t\022\014\n\004note\030\003 \001(\t\022" +
      "\013\n\003lat\030\004 \002(\001\022\013\n\003lng\030\005 \002(\001\022\022\n\ndal_civico\030",
      "\006 \001(\t\022\021\n\tal_civico\030\007 \001(\t\022\030\n\020dal_intersez" +
      "ione\030\010 \001(\t\022\027\n\017al_intersezione\030\t \001(\t\022\021\n\tt" +
      "ipologia\030\n \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Ordinanza_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Ordinanza_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Ordinanza_descriptor,
              new java.lang.String[] { "Id", "Ogetto", "Data", "Dal", "Al", "Tipologia", "Stato", "Vie", },
              eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza.class,
              eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Ordinanza.Builder.class);
          internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Via_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Via_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_services_ordinanzerovereto_data_message_Via_descriptor,
              new java.lang.String[] { "CodiceVia", "DescrizioneVia", "Note", "Lat", "Lng", "DalCivico", "AlCivico", "DalIntersezione", "AlIntersezione", "Tipologia", },
              eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.class,
              eu.trentorise.smartcampus.services.ordinanzerovereto.data.message.Ordinanzerovereto.Via.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
