// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parcheggi.proto

package eu.trentorise.smartcampus.service.parcheggi.data.message;

public final class Parcheggi {
  private Parcheggi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ParcheggioOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string address = 2;
    boolean hasAddress();
    String getAddress();
    
    // required string places = 3;
    boolean hasPlaces();
    String getPlaces();
    
    // optional .it.sayservice.platform.core.message.POI poi = 4;
    boolean hasPoi();
    it.sayservice.platform.core.message.Core.POI getPoi();
    it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder();
  }
  public static final class Parcheggio extends
      com.google.protobuf.GeneratedMessage
      implements ParcheggioOrBuilder {
    // Use Parcheggio.newBuilder() to construct.
    private Parcheggio(Builder builder) {
      super(builder);
    }
    private Parcheggio(boolean noInit) {}
    
    private static final Parcheggio defaultInstance;
    public static Parcheggio getDefaultInstance() {
      return defaultInstance;
    }
    
    public Parcheggio getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.internal_static_eu_trentorise_smartcampus_service_parcheggi_data_message_Parcheggio_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.internal_static_eu_trentorise_smartcampus_service_parcheggi_data_message_Parcheggio_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string address = 2;
    public static final int ADDRESS_FIELD_NUMBER = 2;
    private java.lang.Object address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          address_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string places = 3;
    public static final int PLACES_FIELD_NUMBER = 3;
    private java.lang.Object places_;
    public boolean hasPlaces() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPlaces() {
      java.lang.Object ref = places_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          places_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPlacesBytes() {
      java.lang.Object ref = places_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        places_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .it.sayservice.platform.core.message.POI poi = 4;
    public static final int POI_FIELD_NUMBER = 4;
    private it.sayservice.platform.core.message.Core.POI poi_;
    public boolean hasPoi() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public it.sayservice.platform.core.message.Core.POI getPoi() {
      return poi_;
    }
    public it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder() {
      return poi_;
    }
    
    private void initFields() {
      id_ = "";
      address_ = "";
      places_ = "";
      poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlaces()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPoi()) {
        if (!getPoi().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPlacesBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, poi_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPlacesBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, poi_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.ParcheggioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.internal_static_eu_trentorise_smartcampus_service_parcheggi_data_message_Parcheggio_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.internal_static_eu_trentorise_smartcampus_service_parcheggi_data_message_Parcheggio_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPoiFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        places_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (poiBuilder_ == null) {
          poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
        } else {
          poiBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio build() {
        eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio buildPartial() {
        eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio result = new eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.places_ = places_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (poiBuilder_ == null) {
          result.poi_ = poi_;
        } else {
          result.poi_ = poiBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio) {
          return mergeFrom((eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio other) {
        if (other == eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasPlaces()) {
          setPlaces(other.getPlaces());
        }
        if (other.hasPoi()) {
          mergePoi(other.getPoi());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasAddress()) {
          
          return false;
        }
        if (!hasPlaces()) {
          
          return false;
        }
        if (hasPoi()) {
          if (!getPoi().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              address_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              places_ = input.readBytes();
              break;
            }
            case 34: {
              it.sayservice.platform.core.message.Core.POI.Builder subBuilder = it.sayservice.platform.core.message.Core.POI.newBuilder();
              if (hasPoi()) {
                subBuilder.mergeFrom(getPoi());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPoi(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string address = 2;
      private java.lang.Object address_ = "";
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      void setAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
      }
      
      // required string places = 3;
      private java.lang.Object places_ = "";
      public boolean hasPlaces() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPlaces() {
        java.lang.Object ref = places_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          places_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPlaces(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        places_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlaces() {
        bitField0_ = (bitField0_ & ~0x00000004);
        places_ = getDefaultInstance().getPlaces();
        onChanged();
        return this;
      }
      void setPlaces(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        places_ = value;
        onChanged();
      }
      
      // optional .it.sayservice.platform.core.message.POI poi = 4;
      private it.sayservice.platform.core.message.Core.POI poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder> poiBuilder_;
      public boolean hasPoi() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public it.sayservice.platform.core.message.Core.POI getPoi() {
        if (poiBuilder_ == null) {
          return poi_;
        } else {
          return poiBuilder_.getMessage();
        }
      }
      public Builder setPoi(it.sayservice.platform.core.message.Core.POI value) {
        if (poiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          poi_ = value;
          onChanged();
        } else {
          poiBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setPoi(
          it.sayservice.platform.core.message.Core.POI.Builder builderForValue) {
        if (poiBuilder_ == null) {
          poi_ = builderForValue.build();
          onChanged();
        } else {
          poiBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergePoi(it.sayservice.platform.core.message.Core.POI value) {
        if (poiBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              poi_ != it.sayservice.platform.core.message.Core.POI.getDefaultInstance()) {
            poi_ =
              it.sayservice.platform.core.message.Core.POI.newBuilder(poi_).mergeFrom(value).buildPartial();
          } else {
            poi_ = value;
          }
          onChanged();
        } else {
          poiBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearPoi() {
        if (poiBuilder_ == null) {
          poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
          onChanged();
        } else {
          poiBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public it.sayservice.platform.core.message.Core.POI.Builder getPoiBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getPoiFieldBuilder().getBuilder();
      }
      public it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder() {
        if (poiBuilder_ != null) {
          return poiBuilder_.getMessageOrBuilder();
        } else {
          return poi_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder> 
          getPoiFieldBuilder() {
        if (poiBuilder_ == null) {
          poiBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder>(
                  poi_,
                  getParentForChildren(),
                  isClean());
          poi_ = null;
        }
        return poiBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggio)
    }
    
    static {
      defaultInstance = new Parcheggio(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggio)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_parcheggi_data_message_Parcheggio_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_parcheggi_data_message_Parcheggio_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017parcheggi.proto\0228eu.trentorise.smartca" +
      "mpus.service.parcheggi.data.message\032\ncor" +
      "e.proto\"p\n\nParcheggio\022\n\n\002id\030\001 \002(\t\022\017\n\007add" +
      "ress\030\002 \002(\t\022\016\n\006places\030\003 \002(\t\0225\n\003poi\030\004 \001(\0132" +
      "(.it.sayservice.platform.core.message.PO" +
      "I"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_trentorise_smartcampus_service_parcheggi_data_message_Parcheggio_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_trentorise_smartcampus_service_parcheggi_data_message_Parcheggio_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_parcheggi_data_message_Parcheggio_descriptor,
              new java.lang.String[] { "Id", "Address", "Places", "Poi", },
              eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio.class,
              eu.trentorise.smartcampus.service.parcheggi.data.message.Parcheggi.Parcheggio.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          it.sayservice.platform.core.message.Core.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
